export const TIMER_ACTION_TYPES = {
    SET_CURRENT_HOURS: 'SET_CURRENT_HOURS',
    SET_CURRENT_MINUTES: 'SET_CURRENT_MINUTES',
    SET_CURRENT_SECONDS: 'SET_CURRENT_SECONDS',
    START_TIMER: 'START_TIMER'
}